### ISSUE TITLE
Crash in handler_typed_data calling write_profile

### ISSUE THREAD

**Issue by jimboca** [UniversalDevicesInc-PG3/udi-poly-notification#34]
If error is encountered user my restart the NS to update the profile properly.

```
2022-03-31 20:55:11,148 Thread-49  udi_interface      ERROR    udi_interface:write: Exception in thread
2022-03-31 20:55:11,149 Thread-49  udi_interface      ERROR    udi_interface:write: Thread-49
2022-03-31 20:55:11,149 Thread-49  udi_interface      ERROR    udi_interface:write: :
2022-03-31 20:55:11,150 Thread-49  udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2022-03-31 20:55:11,150 Thread-49  udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2022-03-31 20:55:11,154 Thread-49  udi_interface      ERROR    udi_interface:write: self.run()
2022-03-31 20:55:11,155 Thread-49  udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.8/threading.py", line 870, in run
2022-03-31 20:55:11,158 Thread-49  udi_interface      ERROR    udi_interface:write: self._target(*self._args, **self._kwargs)
2022-03-31 20:55:11,159 Thread-49  udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/00:0d:b9:52:bf:fc_5/nodes/Controller.py", line 503, in handler_typed_data
2022-03-31 20:55:11,162 Thread-49  udi_interface      ERROR    udi_interface:write: self.write_pofile()
2022-03-31 20:55:11,163 Thread-49  udi_interface      ERROR    udi_interface:write: AttributeError
2022-03-31 20:55:11,164 Thread-49  udi_interface      ERROR    udi_interface:write: :
2022-03-31 20:55:11,164 Thread-49  udi_interface      ERROR    udi_interface:write: 'Controller' object has no attribute 'write_pofile'
```

**Comment by jimboca** [comment]
fixed above, still get:
```
2022-04-02 19:32:20,204 MQTT       udi_interface.interface INFO     interface:_connect: MQTT Connected with result code 0 (Success)
2022-04-02 19:32:20,205 MQTT       udi_interface.interface INFO     interface:_connect: MQTT Subscribing to topic: udi/pg3/ns/clients/00:0d:b9:52:ce:50_2 -  MID: 1 Result: 0
2022-04-02 19:32:20,229 MQTT       udi_interface.interface INFO     interface:_subscribe: MQTT Subscribed Succesfully for Message ID: 1 - QoS: (0,)
2022-04-02 19:32:23,223 MainThread udi_interface.custom INFO     custom:_save: Sending data notices to Polyglot.
2022-04-02 19:32:23,225 MainThread udi_interface.interface INFO     interface:addNode: Adding node Notification Controller(controller) [None]
2022-04-02 19:32:23,227 MainThread udi_interface.interface INFO     interface:setController: Using node "controller", driver "ST" for connection status.
2022-04-02 19:32:23,345 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = customtypedparams
2022-04-02 19:32:23,614 Thread-6   udi_interface      WARNING  Controller:handler_config_done: Waiting for all handlers to complete start=None params=False data=False typed_data=False cnt=60
2022-04-02 19:32:24,624 Thread-6   udi_interface      ERROR    Controller:handler_config_done: Unable to start REST Server until config params are correctd (False)
2022-04-02 19:32:24,631 Thread-6   udi_interface      WARNING  Controller:write_profile: No User Messages, define some in Configuration if desired
2022-04-02 19:34:07,151 Thread-12  udi_interface      WARNING  Controller:handler_typed_data: No Pushover Entries in the config: []
2022-04-02 19:34:07,152 Thread-12  udi_interface      WARNING  Controller:handler_typed_data: No Telegram User Bot Entries in the config: []
2022-04-02 19:34:07,153 Thread-12  udi_interface      WARNING  Controller:handler_typed_data: No Notify Nodes
2022-04-02 19:35:12,380 Thread-14  udi_interface      WARNING  Controller:handler_typed_data: No Notify Nodes
2022-04-02 19:35:12,384 Thread-14  udi_interface.interface WARNING  interface:db_getNodeDrivers: po_dev not found in database.
2022-04-02 19:35:12,389 Thread-14  udi_interface.interface WARNING  interface:db_getNodeDrivers: tu_telegram not found in database.
2022-04-02 19:35:13,341 Thread-14  udi_interface      WARNING  Controller:write_profile: Waiting for Service Pushover dev to initialize, timeout in 60 seconds...
2022-04-02 19:35:13,610 Thread-16  udi_interface      WARNING  Pushover:get: try 1/sounds.json #1
2022-04-02 19:35:14,371 Thread-14  udi_interface      ERROR    udi_interface:write: Exception in thread
2022-04-02 19:35:14,371 Thread-14  udi_interface      ERROR    udi_interface:write: Thread-14
2022-04-02 19:35:14,372 Thread-14  udi_interface      ERROR    udi_interface:write: :
2022-04-02 19:35:14,372 Thread-14  udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2022-04-02 19:35:14,373 Thread-14  udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2022-04-02 19:35:14,376 Thread-14  udi_interface      ERROR    udi_interface:write: self.run()
2022-04-02 19:35:14,377 Thread-14  udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.8/threading.py", line 870, in run
2022-04-02 19:35:14,379 Thread-14  udi_interface      ERROR    udi_interface:write: self._target(*self._args, **self._kwargs)
2022-04-02 19:35:14,380 Thread-14  udi_interface      ERROR    udi_interface:write: File "/usr/home/admin/dev/pg3/udi-poly-notification/nodes/Controller.py", line 503, in handler_typed_data
2022-04-02 19:35:14,382 Thread-14  udi_interface      ERROR    udi_interface:write: self.write_profile()
2022-04-02 19:35:14,383 Thread-14  udi_interface      ERROR    udi_interface:write: File "/usr/home/admin/dev/pg3/udi-poly-notification/nodes/Controller.py", line 603, in write_profile
2022-04-02 19:35:14,386 Thread-14  udi_interface      ERROR    udi_interface:write: config_info_nr.append(node.config_info_nr())
2022-04-02 19:35:14,386 Thread-14  udi_interface      ERROR    udi_interface:write: File "/usr/home/admin/dev/pg3/udi-poly-notification/nodes/Pushover.py", line 208, in config_info_nr
2022-04-02 19:35:14,388 Thread-14  udi_interface      ERROR    udi_interface:write: '<li>Example Network Resource settings for Pushover<ul><li>http<li>POST<li>Host:{0}<li>Port:{1}<li>Path: /send?node={2}&Subject=My+Subject&monospace=1&device=1&priority=2<li>Encode URL: not checked<li>Timeout: 5000<li>Mode: Raw Text</ul>'.format(self.controller.rest.ip,self.controller.rest.listen_port,self.address),
2022-04-02 19:35:14,388 Thread-14  udi_interface      ERROR    udi_interface:write: AttributeError
2022-04-02 19:35:14,389 Thread-14  udi_interface      ERROR    udi_interface:write: :
2022-04-02 19:35:14,389 Thread-14  udi_interface      ERROR    udi_interface:write: 'NoneType' object has no attribute 'ip'
```
